[package]
name = "wb-world"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
wb-grid.workspace = true
libm.workspace = true
blake3.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
